### ISSUE TITLE
Game said I won with 2 flags left

### ISSUE THREAD

**Issue by karadouville** [OrkoHunter/Minesweeper#1]
I did an easy game. 

It was the very end of the game, and I thought there was a bug because I couldn't put down a flag, but no, I had just "run out of flags." So I undid a a few flags, and looked around to where I might've incorrectly flagged a square. Sure enough, I found one. I unflagged the improper square and clicked on it, and the game said, "I won!"

It looks like it didn't realize I had unflagged some mines that I had previously flagged.

**Comment by OrkoHunter** [comment]
hmm... The criteria for winning is not about the number of flags remaining. You win when you click the last box not containing a mine. It's up to you how you use the flags. ;)
